project:
  type: website

website:
  title: dhbern.github.io
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://dhbern.github.io/
  repo-url: https://github.com/DHBern/dhbern.github.io/
  issue-url: https://github.com/DHBern/dhbern.github.io/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: Digital Humanities
    tools:
      - icon: github
        url: https://github.com/DHBern/dhbern.github.io/
    left:
      - text: Home
        href: https://www.dh.unibe.ch/
      - text: Studies
        href: https://www.dh.unibe.ch/studium/index_ger.html
      - text: Projects
        href: projects/index.qmd
      - text: People
        href: people/index.qmd
      - text: Services
        href: https://www.dh.unibe.ch/dienstleistungen/index_ger.html

  sidebar:
    style: 'docked'
    collapse-level: 1
    contents:
      - text: Home
        href: index.qmd
      - text: Studies
        href: https://www.dh.unibe.ch/studium/index_ger.html
      - section: Projects
        href: projects/index.qmd
        contents: projects/*/index.qmd
      - section: People
        href: people/index.qmd
        contents: people/*/index.qmd
      - text: Services
        href: https://www.dh.unibe.ch/dienstleistungen/index_ger.html

format:
  html:
    toc: true
    theme:
      - cosmo
      - custom.scss
    code-copy: true
    code-overflow: wrap
    css: styles.css
    mainfont: 'FrutigerNeue'
    linkcolor: '#0074c4'
    link-external-icon: true
    include-in-header:
      - custom-header.html
    page-layout: full
freeze: true

editor: visual
