project:
  type: website

website:
  title: dhbern.github.io
  # favicon: logo.png
  open-graph: true
  twitter-card: true
  site-url: https://dhbern.github.io/
  repo-url: https://github.com/DHBern/dhbern.github.io/
  issue-url: https://github.com/DHBern/dhbern.github.io/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    title: Digital Humanities
    tools:
      - icon: github
        url: https://github.com/DHBern/dhbern.github.io/
    left:
      - text: Studies
        href: https://www.dh.unibe.ch/studium/index_ger.html
      - text: Research
        href: content/projects/index.qmd
      - text: Services
        href: content/services/index.qmd
      - text: About us
        href: https://www.dh.unibe.ch/about_us/team/index_eng.html

  sidebar:
    style: 'docked'
    collapse-level: 1
    contents:
      - text: Blog
        href: /
      - text: Events
        href: /#events
      - text: Projects
        href: content/projects/index.qmd
        contents: content/projects/*/index.qmd
      - text: Services
        href: content/services/index.qmd
        contents: content/services/*/index.qmd

format:
  html:
    toc: true
    toc-location: right
    theme:
      - brand
      - custom.scss
    code-copy: true
    code-overflow: wrap
    citations-hover: true
    crossrefs-hover: true
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    include-in-header:
      - custom-header.html
    page-layout: full
    license: CC BY-SA 4.0

freeze: auto

editor: visual
