project:
  type: website

website:
  title: dhbern.github.io
  # favicon: logo.png
  open-graph: true
  twitter-card: true
  site-url: https://maehr.github.io/dhbern.github.io/projects/
  repo-url: https://github.com/DHBern/dhbern.github.io/
  issue-url: https://github.com/DHBern/dhbern.github.io/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: false
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    title: Digital Humanities
    tools:
      - icon: github
        url: https://github.com/DHBern/dhbern.github.io/
    left:
      - text: Home
        href: https://www.dh.unibe.ch/
      - text: Studies
        href: https://www.dh.unibe.ch/studium/index_ger.html
      - text: Projects
        href: projects/index.qmd
      - text: People
        href: people/index.qmd
      - text: Services
        href: https://www.dh.unibe.ch/dienstleistungen/index_ger.html

  sidebar:
    style: 'docked'
    collapse-level: 1
    contents:
      - text: Home
        href: index.qmd
      - text: Studies
        href: https://www.dh.unibe.ch/studium/index_ger.html
      - section: Projects
        href: projects/index.qmd
        contents: projects/*/index.qmd
      - section: People
        href: people/index.qmd
        contents: people/*/index.qmd
      - text: Services
        href: https://www.dh.unibe.ch/dienstleistungen/index_ger.html

format:
  html:
    toc: true
    toc-location: right
    theme:
      - brand
      - custom.scss
    code-copy: true
    code-overflow: wrap
    citations-hover: true
    crossrefs-hover: true
    css: styles.css
    # mainfont: 'FrutigerNeue'
    # backgroundcolor: '#f8f9fa'
    # fontcolor: '#333333'
    # linkcolor: '#0056b3'
    link-external-icon: true
    link-external-newwindow: true
    include-in-header:
      - custom-header.html
    page-layout: full
    license: CC BY-SA 4.0

freeze: true

editor: visual
