contact_links:
  - name: Are you looking for documentation on dhbern.github.io?
    url: https://DHBern.github.io/dhbern.github.io
    about: Please see the documentation for dhbern.github.io on its GitHub Pages page.
  - name: Do want to discuss dhbern.github.io with the community?
    url: https://github.com/DHBern/dhbern.github.io/discussions
    about: Please see the discussions page for dhbern.github.io.
blank_issues_enabled: true
